/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join the launch waitlist */
        post: operations["joinWaitlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published experiences */
        get: operations["listExperiences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single experience by slug */
        get: operations["getExperience"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences/{slug}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bookable slots within a date range */
        get: operations["getAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a booking (holds a slot, initiates payment) */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request an OTP to a phone number */
        post: operations["requestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify an OTP and issue tokens */
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @example invalid_input */
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
                requestId?: string;
            };
        };
        Money: {
            /**
             * @description Amount in the currency's minor unit (paise for INR)
             * @example 450000
             */
            amountMinor: number;
            /** @example INR */
            currency: string;
        };
        /** @enum {string} */
        Category: "adventure" | "nature_wildlife" | "food_drink" | "arts_creativity" | "learning" | "culture_heritage" | "wellness" | "entertainment" | "community" | "sports" | "local_life" | "events";
        /** @enum {string} */
        ExperienceMode: "local" | "travel";
        /** @enum {string} */
        PolicyTier: "flexible" | "firm" | "weather";
        /** @enum {string} */
        ProviderTier: "professional" | "creator" | "community";
        Provider: {
            id: string;
            name: string;
            tier: components["schemas"]["ProviderTier"];
            verified?: boolean;
        };
        Media: {
            id: string;
            /** @enum {string} */
            type: "image" | "video";
            /** Format: uri */
            url: string;
            /** Format: uri */
            posterUrl?: string;
            alt?: string;
        };
        ExperienceSummary: {
            id: string;
            slug: string;
            title: string;
            location: string;
            category: components["schemas"]["Category"];
            mode: components["schemas"]["ExperienceMode"];
            durationMinutes: number;
            fromPrice: components["schemas"]["Money"];
            /** Format: float */
            rating: number;
            reviewCount?: number;
            hero?: components["schemas"]["Media"];
            provider: components["schemas"]["Provider"];
        };
        Experience: components["schemas"]["ExperienceSummary"] & {
            summary: string;
            description: string;
            highlights?: string[];
            included?: string[];
            policyTier: components["schemas"]["PolicyTier"];
            maxGroupSize?: number;
            gallery: components["schemas"]["Media"][];
        };
        ExperiencePage: {
            items: components["schemas"]["ExperienceSummary"][];
            nextCursor: string | null;
        };
        Slot: {
            id: string;
            /** Format: date-time */
            startsAt: string;
            capacity: number;
            remaining: number;
            price: components["schemas"]["Money"];
        };
        BookingInput: {
            slotId: string;
            guests: number;
        };
        Booking: {
            id: string;
            /** @enum {string} */
            status: "pending_payment" | "confirmed" | "completed" | "cancelled" | "no_show";
            experienceSlug: string;
            slotId: string;
            guests: number;
            total: components["schemas"]["Money"];
            /** Format: date-time */
            createdAt: string;
        };
        WaitlistInput: {
            name?: string;
            /** Format: email */
            email: string;
            source?: string;
        };
        WaitlistEntry: {
            id: string;
            email: string;
            /** Format: date-time */
            createdAt: string;
        };
        AuthTokens: {
            accessToken: string;
            refreshToken: string;
            user: components["schemas"]["User"];
        };
        User: {
            id: string;
            name?: string;
            email?: string;
            phone?: string;
            /** @enum {string} */
            role: "seeker" | "provider" | "admin";
        };
    };
    responses: {
        /** @description Invalid input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    joinWaitlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistInput"];
            };
        };
        responses: {
            /** @description Added (idempotent on email) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    listExperiences: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                category?: components["schemas"]["Category"];
                mode?: components["schemas"]["ExperienceMode"];
                /** @description Free-text search */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of experience summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperiencePage"];
                };
            };
        };
    };
    getExperience: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The experience */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experience"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAvailability: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available slots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingInput"];
            };
        };
        responses: {
            /** @description Booking created in pending_payment */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Slot no longer available (capacity race) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    requestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description E.164 */
                    phone: string;
                };
            };
        };
        responses: {
            /** @description OTP dispatched */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    phone: string;
                    code: string;
                };
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
