/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register pre-launch interest as a traveller or a provider
         * @description Public, rate-limited pre-launch lead capture. The request is discriminated on `audience`. Geography is generic: `marketKey` names a launch market and destination keys name a destination within it, so future markets reuse this shape unchanged.
         *
         *     A returning contact (same audience + normalised WhatsApp) updates its current preferences and attribution and returns `200`; a new contact returns `201`. Notification jobs are written in the same transaction as the lead, so a saved lead is never lost to an unavailable alert target.
         */
        post: operations["createLead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a message from the public contact form
         * @description Public, rate-limited free-text contact. Shipped 2026-08-07 (yuvoy-in/yuvoy-api#5) and verified against production.
         *
         *     **A message is not a lead, and the schema enforces it rather than trusting anyone to remember.** There is no marketing-consent field — its absence is the guarantee, because there is nothing here for a later change to flip to true. Messages are never deduplicated: two questions from one address are two questions. There is no lifecycle status; triage happens in the inbox the alert lands in.
         *
         *     **`202`, never `201`.** It acknowledges receipt and promises nothing about a reply, because the site publishes no reply time and an acknowledgement that implied one would be a commitment nobody made.
         *
         *     Rate limiting has its own bucket, separate from `/leads`: a burst of spam on a public free-text endpoint must not lock a real visitor out of the waitlist, or the reverse.
         */
        post: operations["createMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join the launch waitlist */
        post: operations["joinWaitlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published experiences */
        get: operations["listExperiences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single experience by slug */
        get: operations["getExperience"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences/{slug}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bookable slots within a date range */
        get: operations["getAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a booking (holds a slot, initiates payment) */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request an OTP to a phone number */
        post: operations["requestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify an OTP and issue tokens */
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @example invalid_input */
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
                requestId?: string;
            };
        };
        Money: {
            /**
             * @description Amount in the currency's minor unit (paise for INR)
             * @example 450000
             */
            amountMinor: number;
            /** @example INR */
            currency: string;
        };
        /** @enum {string} */
        Category: "adventure" | "nature_wildlife" | "food_drink" | "arts_creativity" | "learning" | "culture_heritage" | "wellness" | "entertainment" | "community" | "sports" | "local_life" | "events";
        /** @enum {string} */
        ExperienceMode: "local" | "travel";
        /** @enum {string} */
        PolicyTier: "flexible" | "firm" | "weather";
        /** @enum {string} */
        ProviderTier: "professional" | "creator" | "community";
        Provider: {
            id: string;
            name: string;
            tier: components["schemas"]["ProviderTier"];
            verified?: boolean;
        };
        Media: {
            id: string;
            /** @enum {string} */
            type: "image" | "video";
            /** Format: uri */
            url: string;
            /** Format: uri */
            posterUrl?: string;
            alt?: string;
        };
        ExperienceSummary: {
            id: string;
            slug: string;
            title: string;
            location: string;
            category: components["schemas"]["Category"];
            mode: components["schemas"]["ExperienceMode"];
            durationMinutes: number;
            fromPrice: components["schemas"]["Money"];
            /** Format: float */
            rating: number;
            reviewCount?: number;
            hero?: components["schemas"]["Media"];
            provider: components["schemas"]["Provider"];
        };
        Experience: components["schemas"]["ExperienceSummary"] & {
            summary: string;
            description: string;
            highlights?: string[];
            included?: string[];
            policyTier: components["schemas"]["PolicyTier"];
            maxGroupSize?: number;
            gallery: components["schemas"]["Media"][];
        };
        ExperiencePage: {
            items: components["schemas"]["ExperienceSummary"][];
            nextCursor: string | null;
        };
        Slot: {
            id: string;
            /** Format: date-time */
            startsAt: string;
            capacity: number;
            remaining: number;
            price: components["schemas"]["Money"];
        };
        BookingInput: {
            slotId: string;
            guests: number;
        };
        Booking: {
            id: string;
            /** @enum {string} */
            status: "pending_payment" | "confirmed" | "completed" | "cancelled" | "no_show";
            experienceSlug: string;
            slotId: string;
            guests: number;
            total: components["schemas"]["Money"];
            /** Format: date-time */
            createdAt: string;
        };
        WaitlistInput: {
            name?: string;
            /** Format: email */
            email: string;
            source?: string;
        };
        WaitlistEntry: {
            id: string;
            email: string;
            /** Format: date-time */
            createdAt: string;
        };
        AuthTokens: {
            accessToken: string;
            refreshToken: string;
            user: components["schemas"]["User"];
        };
        User: {
            id: string;
            name?: string;
            email?: string;
            phone?: string;
            /** @enum {string} */
            role: "seeker" | "provider" | "admin";
        };
        /**
         * @description Which side of the marketplace the contact is. `provider` matches the existing `User.role` and `Provider` vocabulary in this contract.
         * @enum {string}
         */
        LeadAudience: "traveller" | "provider";
        /**
         * @description Launch market. Extensible; `andaman` is simply the first.
         * @example andaman
         */
        MarketKey: string;
        /**
         * @description A destination within a market, as `<market>/<destination>`.
         * @example andaman/havelock
         */
        DestinationKey: string;
        /** @enum {string} */
        InterestGroup: "diving_water" | "boats_islands" | "food_culture" | "other";
        /**
         * @description Where the visitor arrived from. Campaign routes set this.
         * @default web
         * @enum {string}
         */
        LeadSource: "ferry" | "kiosk" | "hotel" | "instagram" | "direct" | "web";
        /** @description Campaign attribution. Never treated as identifying data. */
        Utm: {
            source?: string;
            medium?: string;
            campaign?: string;
            content?: string;
            term?: string;
        };
        /**
         * @description Contact rule, as deployed (yuvoy-in/yuvoy-api#4, live 2026-08-07): **at least one of `whatsapp` or `email`**, for both audiences. Deduplication uses the normalised contact — WhatsApp number when present, else email — so an operator with no phone number deduplicates on their address.
         *
         *     A request carrying neither is rejected on the field name **`contact`**, not `whatsapp`, because a form may legitimately no longer render a WhatsApp input to point an error at.
         *
         *     **The frontend is deliberately stricter than this and requires `email` of everyone** (owner direction, 2026-08-07): it is the channel the launch announcement is actually sent on — free, no messaging-platform template approval, and it reaches every country. That is a product decision enforced in the forms, not a contract constraint; the API accepts either channel and this document describes the API.
         */
        LeadInputBase: {
            audience: components["schemas"]["LeadAudience"];
            contactName: string;
            /**
             * @description Normalised to E.164 server-side.
             * @example +919000000000
             */
            whatsapp?: string;
            /** Format: email */
            email?: string;
            /**
             * @description Must be true. Acknowledges the Privacy Policy and Terms.
             * @constant
             */
            privacyAccepted: true;
            /**
             * @description Separate, optional, unchecked by default.
             * @default false
             */
            marketingOptIn: boolean;
            marketKey: components["schemas"]["MarketKey"];
            source?: components["schemas"]["LeadSource"];
            utm?: components["schemas"]["Utm"];
            /** @description Honeypot. Left empty by real visitors; a non-empty value is handled server-side and never becomes an actionable lead. */
            website?: string;
        };
        TravellerLeadInput: components["schemas"]["LeadInputBase"] & {
            /** @constant */
            audience?: "traveller";
            primaryDestinationKey?: components["schemas"]["DestinationKey"];
            interests?: components["schemas"]["InterestGroup"][];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            audience: "traveller";
        };
        ProviderLeadInput: components["schemas"]["LeadInputBase"] & {
            /** @constant */
            audience?: "provider";
            businessName: string;
            coverageDestinationKeys?: components["schemas"]["DestinationKey"][];
            primaryInterest?: components["schemas"]["InterestGroup"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            audience: "provider";
        };
        LeadInput: components["schemas"]["TravellerLeadInput"] | components["schemas"]["ProviderLeadInput"];
        /** @description A message from the public contact form. Deliberately not a lead: no marketing consent, no market or destination, no attribution beyond the campaign `source`. */
        MessageInput: {
            name: string;
            /** Format: email */
            email: string;
            topic: components["schemas"]["MessageTopic"];
            /** @description Capped at 4000 **characters, not bytes** — 4000 multi-byte characters is still 4000 characters, so a message written in Hindi is not silently penalised. 4001 is a 400. */
            message: string;
            source?: components["schemas"]["LeadSource"];
            /** @description Honeypot. A filled value answers `202` exactly as a real submission does, and writes neither a row nor a notification — a bot must not be able to tell it was caught. */
            website?: string;
        };
        /**
         * @description What the message is about. Anything outside this list is a 400. There is deliberately no "a trip or experience" option: nothing is bookable yet, so offering it would invite a question nobody can answer.
         * @enum {string}
         */
        MessageTopic: "general" | "feedback" | "listing" | "partnership";
        /** @description Acknowledges receipt and nothing else. No reply-time promise, because the site publishes none. */
        MessageAcceptance: {
            /** Format: uuid */
            id: string;
            /** @constant */
            status: "received";
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Deliberately minimal. It confirms the lead was recorded and carries no queue position, priority, or follow-up guarantee. */
        LeadAcceptance: {
            /** Format: uuid */
            id: string;
            audience: components["schemas"]["LeadAudience"];
            /** @enum {string} */
            status: "recorded" | "updated";
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * @description Internal follow-up lifecycle for a lead, tracked ops-side only. It is never accepted on a request and never returned in `LeadAcceptance` — a visitor's submission carries no signal about how their registration is being worked. Documented here for the internal ops tooling that reads and updates it directly against the database; no public endpoint reads or writes this value yet.
         * @default new
         * @enum {string}
         */
        LeadStatus: "new" | "contacted" | "qualified" | "disqualified";
    };
    responses: {
        /** @description Invalid input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A dependency is unavailable; the request was not recorded */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createLead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadInput"];
            };
        };
        responses: {
            /** @description Existing lead updated (same audience + WhatsApp) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadAcceptance"];
                };
            };
            /** @description New lead recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadAcceptance"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageInput"];
            };
        };
        responses: {
            /** @description Message received */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageAcceptance"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    joinWaitlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistInput"];
            };
        };
        responses: {
            /** @description Added (idempotent on email) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    listExperiences: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                category?: components["schemas"]["Category"];
                mode?: components["schemas"]["ExperienceMode"];
                /** @description Free-text search */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of experience summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperiencePage"];
                };
            };
        };
    };
    getExperience: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The experience */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experience"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAvailability: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available slots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingInput"];
            };
        };
        responses: {
            /** @description Booking created in pending_payment */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Slot no longer available (capacity race) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    requestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description E.164 */
                    phone: string;
                };
            };
        };
        responses: {
            /** @description OTP dispatched */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    phone: string;
                    code: string;
                };
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
