import Image from "next/image";
import { cn } from "@/lib/cn";

/**
 * The Yuvoy wordmark — the owner-delivered horizontal lockup (2026-08-06):
 * the ensō with its terra dot, the tracked YUVOY caps, the handwritten
 * "Experience more." and its tapered underline, all one drawing. It replaces
 * the previous composed wordmark (square mark + Satoshi caps + kicker);
 * the square cut-out marks still ship for the favicon, app icon and OG card.
 *
 * Two surface variants, generated by scripts/generate-header-lockup.mjs and
 * never hand-edited: the delivered cream/terra-soft drawing for forest
 * surfaces, and a forest/terra-deep recolour for cream ones — the §1 tone
 * pairings. **Both render and cross-fade on opacity**, so the header's
 * colour change over the cover never waits on a fetch.
 *
 * `unoptimized`: SVG needs no optimiser pass, and this keeps
 * `dangerouslyAllowSVG` out of the image config (same call as the veil).
 *
 * Size it from outside with a height class — the default `h-14` nearly
 * fills the 64px header bar (4px of air each side; owner stepped it up
 * three times, 2026-08-06 — this is as far as the bar allows). The menu
 * bar shares it and the footer passes `h-20`. tailwind-merge keeps the
 * later height. The drawing's 3.2:1 ratio provides the width.
 */
const LOCKUP = { width: 1600, height: 500 } as const;

const VARIANTS = [
  { src: "/brand/yuvoy-lockup-on-light.svg", dark: false },
  { src: "/brand/yuvoy-lockup-on-dark.svg", dark: true },
] as const;

export function Wordmark({
  className,
  tone = "onLight",
}: {
  className?: string;
  tone?: "onLight" | "onDark";
}) {
  const onDark = tone === "onDark";
  return (
    <span
      role="img"
      aria-label="Yuvoy — Experience more."
      className={cn("relative inline-flex h-14", className)}
    >
      {VARIANTS.map(({ src, dark }) => (
        <Image
          key={src}
          unoptimized
          src={src}
          alt=""
          aria-hidden
          width={LOCKUP.width}
          height={LOCKUP.height}
          priority
          className={cn(
            "h-full w-auto transition-opacity duration-300",
            dark && "absolute inset-y-0 left-0",
            (dark ? onDark : !onDark) ? "opacity-100" : "opacity-0",
          )}
        />
      ))}
    </span>
  );
}
