import Image from "next/image";
import { cn } from "@/lib/cn";

/**
 * The Yuvoy wordmark — the owner-delivered horizontal lockup (2026-08-06):
 * the ensō with its terra dot, the tracked YUVOY caps, the handwritten
 * "Experience more." and its tapered underline, all one drawing. It replaces
 * the previous composed wordmark (square mark + Satoshi caps + kicker);
 * the square cut-out marks still ship for the favicon, app icon and OG card.
 *
 * Two surface variants, generated by scripts/generate-header-lockup.mjs and
 * never hand-edited: the delivered paper/terra-soft drawing for forest
 * surfaces, and a forest/terra-deep recolour for paper ones — the §1 tone
 * pairings. **Both render and cross-fade on opacity**, so the header's
 * colour change over the cover never waits on a fetch.
 *
 * `unoptimized`: SVG needs no optimiser pass, and this keeps
 * `dangerouslyAllowSVG` out of the image config (same call as the veil).
 * Deliberately NOT `priority`: both variants render for the cross-fade, so
 * preloading would queue two images on every page when one is invisible.
 * They load eagerly instead — no preload link, but no lazy-load delay on an
 * above-the-fold mark either.
 *
 * Size it from outside with a height class, and the size now means the
 * DRAWING's size: the generated variants crop the delivered canvas's empty
 * margins away, which is what made three owner size-steps look identical.
 * Default is `h-10 sm:h-12` — a true 48px of art in the 64px bar from `sm`
 * up (8px of air each side; owner settled here after seeing 56px), one step
 * down on phones where the width would crowd the centre link. The menu bar
 * shares it; the footer passes `h-20`.
 * tailwind-merge keeps the later height; the art's ~3.6:1 ratio sets width.
 */
/* The cropped art box the generator emits (1247x347, ~3.6:1) — not the
   delivered 1600x500 canvas, which carries a third of its height in empty
   margin. See scripts/generate-header-lockup.mjs. */
const LOCKUP = { width: 1247, height: 347 } as const;

const VARIANTS = [
  { src: "/brand/yuvoy-lockup-on-light.svg", dark: false },
  { src: "/brand/yuvoy-lockup-on-dark.svg", dark: true },
] as const;

export function Wordmark({
  className,
  tone = "onLight",
}: {
  className?: string;
  tone?: "onLight" | "onDark";
}) {
  const onDark = tone === "onDark";
  return (
    <span
      role="img"
      aria-label="Yuvoy · Experience more."
      className={cn("relative inline-flex h-10 sm:h-12", className)}
    >
      {VARIANTS.map(({ src, dark }) => (
        <Image
          key={src}
          unoptimized
          src={src}
          alt=""
          aria-hidden
          width={LOCKUP.width}
          height={LOCKUP.height}
          // `loading="eager"` but NOT `priority`: the header is above the
          // fold so lazy-loading it costs LCP (Next warns), while
          // `priority` would also inject a preload link for BOTH variants
          // on every page — which is what pushed the e2e structure specs
          // past network idle. Eager without the preload is the middle.
          loading="eager"
          className={cn(
            "h-full w-auto transition-opacity duration-300",
            dark && "absolute inset-y-0 left-0",
            (dark ? onDark : !onDark) ? "opacity-100" : "opacity-0",
          )}
        />
      ))}
    </span>
  );
}
