/**
 * Every icon the site serves, derived from the vector mark.
 * Never hand-edit the outputs; change this script and re-run:
 *
 *   node scripts/generate-icons.mjs
 *
 * Source is `public/brand/yuvoy-mark-vector-cream.svg` — the ensō alone, no
 * wordmark, cream strokes with the terracotta dot — itself generated by
 * `generate-vector-brand.mjs` from the delivered master.
 *
 * ## Why the mark sits on a forest tile
 *
 * A favicon has no page around it. It is drawn on a browser tab whose colour
 * the site does not control and cannot predict — light, dark, or whatever a
 * theme extension decided — so a transparent cream mark disappears on a light
 * tab and a transparent forest one disappears on a dark tab. The tile gives
 * the mark its own ground, which is design system §2's existing rule for
 * "where an icon needs a body". **A tile must never appear in the page
 * itself**; there it would draw a green box around the mark.
 *
 * ## Why this replaced the raster pipeline
 *
 * The previous icons came from `generate-brand-assets.py`, which masked a
 * raster of white strokes on black. That left a soft rectangular halo around
 * the terracotta dot — visible at 512px and muddy at 32px — because the dot
 * was recovered from a bitmap rather than drawn. These are rasterised from
 * the vector, so every size is exact and the dot is a circle at 16px.
 *
 * ## What it emits
 *
 *   src/app/icon.svg      the primary favicon. Vector, ~22KB, any size.
 *   src/app/icon.png      512px. Android, PWA, and the Organization logo.
 *   src/app/apple-icon.png 180px. iOS home screen; must be opaque, and is.
 *   src/app/favicon.ico   16/32/48, for anything that ignores the SVG.
 *   public/brand/yuvoy-mark.png  512px, the Open Graph card's mark.
 *
 * Next's file conventions pick all of these up from `src/app` automatically
 * and emit the right `<link>` tags, so nothing needs registering in metadata.
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const require = createRequire(import.meta.url);
const pnpmDir = join(root, "node_modules/.pnpm");
const sharpEntry = readdirSync(pnpmDir).find((d) => d.startsWith("sharp@"));
if (!sharpEntry) throw new Error("sharp not found in the pnpm store");
const sharp = require(join(pnpmDir, sharpEntry, "node_modules/sharp"));

const FOREST = "#16362E";
const SRC = join(root, "public/brand/yuvoy-mark-vector-cream.svg");

/**
 * How much of the tile is margin, per side.
 *
 * 11% is measured rather than picked: the ensō's brush strokes already carry
 * their own optical margin where the ring opens, so the usual 15–20% icon
 * padding leaves it looking small and lost in its tile at 16px, which is the
 * size that decides whether a favicon is recognisable at all.
 */
const PADDING = 0.11;

const source = readFileSync(SRC, "utf8");

const viewBoxMatch = source.match(/viewBox="([^"]+)"/);
if (!viewBoxMatch) throw new Error(`no viewBox in ${SRC}`);
const [vbX, vbY, vbW, vbH] = viewBoxMatch[1].trim().split(/\s+/).map(Number);

/** The mark's own paths, without its `<svg>` wrapper. */
const inner = source
  .replace(/^[\s\S]*?<svg[^>]*>/, "")
  .replace(/<\/svg>\s*$/, "")
  .trim();

/*
  The tile is square and the mark is not (592 × 561), so the canvas is the
  mark's longer edge plus padding, and the mark is centred inside it by
  translating half the difference on each axis. Deriving this from the
  viewBox rather than hard-coding a square means a redrawn mark still lands
  centred without anyone re-measuring it.
*/
const longest = Math.max(vbW, vbH);
const tile = longest / (1 - PADDING * 2);
const offsetX = (tile - vbW) / 2 - vbX;
const offsetY = (tile - vbH) / 2 - vbY;

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${round(tile)} ${round(tile)}" width="${round(tile)}" height="${round(tile)}" fill="none">
  <!-- Generated by scripts/generate-icons.mjs; do not hand-edit. -->
  <rect width="${round(tile)}" height="${round(tile)}" fill="${FOREST}"/>
  <g transform="translate(${round(offsetX)} ${round(offsetY)})">
${indent(inner)}
  </g>
</svg>
`;

function round(n) {
  return Math.round(n * 100) / 100;
}

function indent(block) {
  return block
    .split("\n")
    .map((line) => (line.trim() ? `    ${line.trim()}` : ""))
    .join("\n");
}

writeFileSync(join(root, "src/app/icon.svg"), svg);
console.log("src/app/icon.svg");

const buffer = Buffer.from(svg);
const png = (size) =>
  sharp(buffer, { density: 384 }).resize(size, size).png().toBuffer();

for (const [path, size] of [
  ["src/app/icon.png", 512],
  ["src/app/apple-icon.png", 180],
  ["public/brand/yuvoy-mark.png", 512],
]) {
  writeFileSync(join(root, path), await png(size));
  console.log(`${path}  ${size}x${size}`);
}

/*
  A multi-size .ico, written by hand because sharp cannot emit the container
  and a dependency for six kilobytes of header would be silly.

  Every entry is a PNG rather than a BMP bitmap. The ICO format has allowed
  that since Windows Vista, every browser that still reads .ico at all
  supports it, and it avoids hand-rolling BMP's bottom-up rows and AND mask —
  which is where hand-written .ico files usually go wrong.
*/
const ICO_SIZES = [16, 32, 48];
const images = await Promise.all(ICO_SIZES.map(png));

const header = Buffer.alloc(6);
header.writeUInt16LE(0, 0); // reserved
header.writeUInt16LE(1, 2); // type 1 = icon
header.writeUInt16LE(images.length, 4);

let offset = 6 + images.length * 16;
const entries = images.map((image, i) => {
  const entry = Buffer.alloc(16);
  // 0 means 256 in this field; none of our sizes reach it, but the encoding
  // is worth being explicit about for whoever adds a 256px entry later.
  entry.writeUInt8(ICO_SIZES[i] >= 256 ? 0 : ICO_SIZES[i], 0);
  entry.writeUInt8(ICO_SIZES[i] >= 256 ? 0 : ICO_SIZES[i], 1);
  entry.writeUInt8(0, 2); // palette size — 0 for true colour
  entry.writeUInt8(0, 3); // reserved
  entry.writeUInt16LE(1, 4); // colour planes
  entry.writeUInt16LE(32, 6); // bits per pixel
  entry.writeUInt32LE(image.length, 8);
  entry.writeUInt32LE(offset, 12);
  offset += image.length;
  return entry;
});

writeFileSync(
  join(root, "src/app/favicon.ico"),
  Buffer.concat([header, ...entries, ...images]),
);
console.log(`src/app/favicon.ico  ${ICO_SIZES.join("/")}`);
